name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.1.0

      - name: Install Node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: 12

      - run: npm ci

      - run: npm run package

      - uses: ./

      - run: npm run markdownlint

      - uses: ./
        if: success() || failure()
        with:
          action: remove

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 13]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.1.0

      - name: Install Node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run lint

      - run: npm test

      - run: npm run build
